discord:
  clientToken: YOUR_DISCORD_TOKEN
  msgChannelId: DISCORD_CHANNEL_ID
gmail:
  credFile: credentials.json
  videoLabel:
    - name: videoCamNotifications
  choreLabel:
    - name: googleCalendarChores
    msgChannelOverride: DISCORD_CHANNEL_ID
